default:    &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  host:     localhost

development:
  <<:       *default
  database: southy_development

test:
  <<:       *default
  database: southy_test

production:
  <<:       *default
  database: southy_production
